/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedCreateLinkRouteImport } from './routes/_authenticated/create-link'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated/links'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSuspendedRouteImport } from './routes/_authenticated/suspended'
import { Route as AuthenticatedWithdrawalsRouteImport } from './routes/_authenticated/withdrawals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreateLinkRoute = AuthenticatedCreateLinkRouteImport.update({
  id: '/create-link',
  path: '/create-link',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuspendedRoute = AuthenticatedSuspendedRouteImport.update({
  id: '/suspended',
  path: '/suspended',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWithdrawalsRoute =
  AuthenticatedWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-link': typeof AuthenticatedCreateLinkRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/links': typeof AuthenticatedLinksRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/suspended': typeof AuthenticatedSuspendedRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-link': typeof AuthenticatedCreateLinkRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/links': typeof AuthenticatedLinksRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/suspended': typeof AuthenticatedSuspendedRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/create-link': typeof AuthenticatedCreateLinkRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/links': typeof AuthenticatedLinksRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/suspended': typeof AuthenticatedSuspendedRoute
  '/_authenticated/withdrawals': typeof AuthenticatedWithdrawalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/create-link'
    | '/dashboard'
    | '/links'
    | '/pending'
    | '/profile'
    | '/suspended'
    | '/withdrawals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/create-link'
    | '/dashboard'
    | '/links'
    | '/pending'
    | '/profile'
    | '/suspended'
    | '/withdrawals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/create-link'
    | '/_authenticated/dashboard'
    | '/_authenticated/links'
    | '/_authenticated/pending'
    | '/_authenticated/profile'
    | '/_authenticated/suspended'
    | '/_authenticated/withdrawals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/create-link': {
      id: '/_authenticated/create-link'
      path: '/create-link'
      fullPath: '/create-link'
      preLoaderRoute: typeof AuthenticatedCreateLinkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suspended': {
      id: '/_authenticated/suspended'
      path: '/suspended'
      fullPath: '/suspended'
      preLoaderRoute: typeof AuthenticatedSuspendedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/withdrawals': {
      id: '/_authenticated/withdrawals'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof AuthenticatedWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreateLinkRoute: typeof AuthenticatedCreateLinkRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSuspendedRoute: typeof AuthenticatedSuspendedRoute
  AuthenticatedWithdrawalsRoute: typeof AuthenticatedWithdrawalsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreateLinkRoute: AuthenticatedCreateLinkRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLinksRoute: AuthenticatedLinksRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSuspendedRoute: AuthenticatedSuspendedRoute,
  AuthenticatedWithdrawalsRoute: AuthenticatedWithdrawalsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
